### ISSUE TITLE
onHint tab doesn't work with custom lookup function

### ISSUE THREAD

**Issue by Woet** [devbridge/jQuery-Autocomplete#836]
Hi,

Thanks for the great library! I've been running into some issues with onHint tabbing throwing errors and I narrowed it down to it happening whenever a custom lookup function is being used. You can find a working test case here: https://jsfiddle.net/4yezorkp/3/

This code works perfectly fine:
```js
$("#object").autocomplete({
	onHint: true,
  
	lookup: ['foooooooooo', 'baaaaaaaaaaaaaaar']
});
```

But this one throws an error when using tab to select the hint:
```js
$("#function").autocomplete({
	onHint: true,
  
	lookup: function(query, done) {
  	done({
			suggestions: [
      	{ value: 'foooooooooo' },
        { value: 'baaaaaaaaaaaaaaar' }
			]
		});
  }
});
```

And here is the actual error:
```
jquery.autocomplete.js:938 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Autocomplete.onSelect (jquery.autocomplete.js:938:58)
    at Autocomplete.select (jquery.autocomplete.js:866:18)
    at Autocomplete.selectHint (jquery.autocomplete.js:860:18)
    at Autocomplete.onKeyPress (jquery.autocomplete.js:408:30)
    at HTMLInputElement.<anonymous> (jquery.autocomplete.js:212:68)
    at HTMLInputElement.dispatch (jquery-3.6.0.min.js:2:43064)
    at HTMLInputElement.v.handle (jquery-3.6.0.min.js:2:41048)
```

Let me know if I can help in any way.

**Comment by tkirda** [comment]
Feel free to submit a PR if you know what is the issue.

**Comment by tkirda** [comment]
Closing as aged. This was filed against a pre-2.0 codebase that has since been substantially reworked — the source is now TypeScript, the build and CI pipeline are different, and a number of relevant code paths around positioning, selection, and event flow have changed in `2.0.1`.

If this still reproduces against current `master`, please open a new issue with the autocomplete options used and a short steps-to-reproduce.
